repos:
-   repo: https://github.com/igrr/astyle_py.git
    rev: v1.1.0
    hooks:
    -   id: astyle_py
        args: ['--style=otbs', '--attach-namespaces', '--attach-classes', '--indent=spaces=4', '--convert-tabs', '--align-pointer=name', '--align-reference=name', '--keep-one-line-statements', '--pad-header', '--pad-oper']
        exclude: 'network_provisioning/proto-c'
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
-   repo: local
    hooks:
    -   id: consistency_check
        name: Repo consistency checks
        language: python
        entry: python .github/consistency_check.py
        pass_filenames: false
        additional_dependencies:
            - "toml; python_version < '3.11'"
            - pyyaml
-   repo: https://github.com/espressif/esp-idf-kconfig.git
    rev: v2.5.0
    hooks:
    -   id: check-kconfig-files
    -   id: check-deprecated-kconfig-options
